name: loja
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.3.8"

dependencies:
  built_value: ^8.4.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  http: ^0.13.5
  provider: ^4.0.4
  response: ^1.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/inicial.png
    - assets/images/logo.png
    - assets/images/search.png
    - assets/images/bateria.png
    - assets/images/seta.png
    - assets/images/carrinho.png
    - assets/images/guitarra.png
